version: '3.8'

services:
  jobscout_landing_service:
    image: jobscout_landing_image:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 50s
      restart_policy:
        condition: on-failure
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 3
    ports:
      - "3000:3000"
